import React from 'react';
import { View, Text } from 'react-native';

const DATA = [

    {
        id: '1',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '2',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '3',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '4',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '5',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '6',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '7',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '8',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '9',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '10',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '11',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    {
        id: '12',
        videoUri: {uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'},
        isAgree: true,
        isDisagree: false,
        poster: 'userID',
        likes: 56,
        shares: 842,
        question: 'Do you believe that deadlists should be done with a forward grip or an alternate grip?',
        state: 'Texas',
        city: 'Austin',
        county: 'Travis County',
    },
    
];

export default DATA;